# Generated by Django 4.2.4 on 2023-08-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=15)),
                ('repeat_password', models.CharField(max_length=15)),
            ],
        ),
    ]
